'use strict';
/* ============================================================
   precompute.js — Run fcose layout headlessly, save positions
   Usage: cd scripts && npm run precompute
   Output: ../js/data/positions.js
   ============================================================ */

const cytoscape = require('cytoscape');
const fcose     = require('cytoscape-fcose');
const fs        = require('fs');
const path      = require('path');

cytoscape.use(fcose);

/* ── Polyfill browser globals used by data files ───────────── */
global.window = global;

const ROOT = path.join(__dirname, '..');

function load(relPath) {
  const code = fs.readFileSync(path.join(ROOT, relPath), 'utf8');
  // eslint-disable-next-line no-eval
  eval(code);
}

/* ── Load config first (defines makeNode / makeEdge) ─────── */
load('js/config.js');

/* ── Load all node data files ────────────────────────────── */
const dataFiles = [
  'markets', 'institutions', 'instruments', 'concepts',
  'strategies', 'participants', 'metrics', 'events', 'currency',
];
for (const f of dataFiles) load(`js/data/${f}.js`);

/* ── Load edges ───────────────────────────────────────────── */
load('js/data/edges.js');

/* ── Gather elements ──────────────────────────────────────── */
const nodes = [
  ...(global.NODES_MARKETS      || []),
  ...(global.NODES_INSTRUMENTS  || []),
  ...(global.NODES_INSTITUTIONS || []),
  ...(global.NODES_CONCEPTS     || []),
  ...(global.NODES_STRATEGIES   || []),
  ...(global.NODES_PARTICIPANTS || []),
  ...(global.NODES_METRICS      || []),
  ...(global.NODES_EVENTS       || []),
  ...(global.NODES_CURRENCY     || []),
];

const nodeIdSet = new Set(nodes.map(n => n.data.id));
const edges = (global.EDGES || []).filter(e =>
  nodeIdSet.has(e.data.source) && nodeIdSet.has(e.data.target)
);

console.log(`Loaded ${nodes.length} nodes, ${edges.length} edges`);

/* ── Create headless Cytoscape instance ───────────────────── */
const cy = cytoscape({
  headless:     true,
  styleEnabled: false,
  elements:     [...nodes, ...edges],
});

/* ── Run fcose layout (same quality as browser, no animation) */
const layout = cy.layout({
  name:    'fcose',
  quality: 'proof',
  randomize: false,
  animate:   false,
  fit:       true,
  padding:   60,
  nodeDimensionsIncludeLabels: false,
  uniformNodeDimensions:       false,
  packComponents:              true,
  nodeRepulsion:      6500,
  idealEdgeLength:    90,
  edgeElasticity:     0.45,
  nestingFactor:      0.1,
  numIter:            2500,
  gravity:            0.25,
  gravityRange:       3.8,
  initialEnergyOnIncremental: 0.5,
});

layout.on('layoutstop', () => {
  const positions = {};
  cy.nodes().forEach(n => {
    const p = n.position();
    positions[n.id()] = {
      x: parseFloat(p.x.toFixed(1)),
      y: parseFloat(p.y.toFixed(1)),
    };
  });

  const out =
    `/* Auto-generated by scripts/precompute.js — do not hand-edit.\n` +
    `   Re-run: cd scripts && npm run precompute */\n` +
    `window.PRECOMPUTED_POSITIONS = ${JSON.stringify(positions, null, 2)};\n`;

  const outPath = path.join(ROOT, 'js', 'data', 'positions.js');
  fs.writeFileSync(outPath, out, 'utf8');
  const kb = (fs.statSync(outPath).size / 1024).toFixed(1);
  console.log(`✓ Wrote positions for ${Object.keys(positions).length} nodes → js/data/positions.js (${kb} KB)`);
});

layout.run();
