'use strict';
/* ============================================================
   precompute.js — Run fcose layout for all 6 graph views
   Usage: cd scripts && npm run precompute
   Output: ../js/data/positions.js
   ============================================================ */

const cytoscape = require('cytoscape');
const fcose     = require('cytoscape-fcose');
const fs        = require('fs');
const path      = require('path');

cytoscape.use(fcose);

/* ── Polyfill browser globals ─────────────────────────────── */
global.window = global;

const ROOT = path.join(__dirname, '..');

function load(relPath) {
  const code = fs.readFileSync(path.join(ROOT, relPath), 'utf8');
  // eslint-disable-next-line no-eval
  eval(code);
}

load('js/config.js');

const dataFiles = [
  'markets', 'institutions', 'instruments', 'concepts',
  'strategies', 'participants', 'metrics', 'events', 'currency',
];
for (const f of dataFiles) load(`js/data/${f}.js`);
load('js/data/edges.js');

/* ── All nodes & edges ────────────────────────────────────── */
const ALL_NODES = [
  ...(global.NODES_MARKETS      || []),
  ...(global.NODES_INSTRUMENTS  || []),
  ...(global.NODES_INSTITUTIONS || []),
  ...(global.NODES_CONCEPTS     || []),
  ...(global.NODES_STRATEGIES   || []),
  ...(global.NODES_PARTICIPANTS || []),
  ...(global.NODES_METRICS      || []),
  ...(global.NODES_EVENTS       || []),
  ...(global.NODES_CURRENCY     || []),
];
const ALL_EDGES = global.EDGES || [];

/* ── View definitions (mirrors HTML nodeFilters) ─────────── */
const VIEWS = [
  {
    key: 'full',
    filter: null,
  },
  {
    key: 'us',
    filter: d => d.country === 'US' || d.country === 'BOTH',
  },
  {
    key: 'indonesia',
    filter: d => d.country === 'ID' || d.country === 'BOTH',
  },
  {
    key: 'instruments',
    filter: d => ['instruments', 'markets', 'concepts', 'currency', 'institutions'].includes(d.category),
  },
  {
    key: 'strategies',
    filter: d => ['strategies', 'metrics', 'instruments', 'concepts', 'participants'].includes(d.category),
  },
  {
    key: 'events',
    filter: d => ['events', 'institutions', 'markets', 'concepts', 'currency', 'instruments'].includes(d.category),
  },
];

const LAYOUT_OPTS = {
  name:    'fcose',
  quality: 'proof',
  randomize: false,
  animate:   false,
  fit:       true,
  padding:   60,
  nodeDimensionsIncludeLabels: false,
  uniformNodeDimensions:       false,
  packComponents:              true,
  nodeRepulsion:      6500,
  idealEdgeLength:    90,
  edgeElasticity:     0.45,
  nestingFactor:      0.1,
  numIter:            2500,
  gravity:            0.25,
  gravityRange:       3.8,
  initialEnergyOnIncremental: 0.5,
};

/* ── Run layout for a node/edge subset ────────────────────── */
function runLayout(nodes, edges) {
  return new Promise(resolve => {
    const cy = cytoscape({
      headless:     true,
      styleEnabled: false,
      elements:     [...nodes, ...edges],
    });

    const layout = cy.layout(LAYOUT_OPTS);

    layout.on('layoutstop', () => {
      const positions = {};
      cy.nodes().forEach(n => {
        const p = n.position();
        positions[n.id()] = {
          x: parseFloat(p.x.toFixed(1)),
          y: parseFloat(p.y.toFixed(1)),
        };
      });
      resolve(positions);
    });

    layout.run();
  });
}

/* ── Main ─────────────────────────────────────────────────── */
async function main() {
  const allPositions = {};
  const start = Date.now();

  for (const view of VIEWS) {
    const nodes = view.filter
      ? ALL_NODES.filter(n => view.filter(n.data))
      : ALL_NODES;
    const nodeIdSet = new Set(nodes.map(n => n.data.id));
    const edges = ALL_EDGES.filter(e =>
      nodeIdSet.has(e.data.source) && nodeIdSet.has(e.data.target)
    );

    process.stdout.write(`  [${view.key}]  ${nodes.length} nodes, ${edges.length} edges … `);
    const t = Date.now();
    allPositions[view.key] = await runLayout(nodes, edges);
    console.log(`done (${((Date.now() - t) / 1000).toFixed(1)}s)`);
  }

  const outPath = path.join(ROOT, 'js', 'data', 'positions.js');
  const json    = JSON.stringify(allPositions, null, 2);
  const out     =
    `/* Auto-generated by scripts/precompute.js — do not hand-edit.\n` +
    `   Re-run: cd scripts && npm run precompute */\n` +
    `window.PRECOMPUTED_POSITIONS = ${json};\n`;

  fs.writeFileSync(outPath, out, 'utf8');
  const kb    = (fs.statSync(outPath).size / 1024).toFixed(1);
  const total = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`\n✓  ${outPath}  (${kb} KB, ${total}s total)`);
}

main().catch(err => { console.error(err); process.exit(1); });
